// Movie Database
const MOVIES = [
  { id: 1, title: "Dune: Part Two", year: 2024, rating: 8.8, genre: ["Sci-Fi", "Adventure"], runtime: "2h 46m", director: "Denis Villeneuve", cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"], poster: "https://via.placeholder.com/300x450/1a1a2e/c8a96e?text=Dune+2", backdrop: "https://via.placeholder.com/1400x600/0d1117/c8a96e?text=Dune+Part+Two", desc: "Paul Atreides unites with Chani and the Fremen to wage war against the conspirators who destroyed his family.", trending: true, color: "#c8a96e" },
  { id: 2, title: "Oppenheimer", year: 2023, rating: 8.9, genre: ["Drama", "History"], runtime: "3h 1m", director: "Christopher Nolan", cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"], poster: "https://via.placeholder.com/300x450/2d1b00/ff8c00?text=Oppenheimer", backdrop: "https://via.placeholder.com/1400x600/1a0f00/ff8c00?text=Oppenheimer", desc: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", trending: true, color: "#ff8c00" },
  { id: 3, title: "Poor Things", year: 2023, rating: 8.0, genre: ["Fantasy", "Comedy"], runtime: "2h 21m", director: "Yorgos Lanthimos", cast: ["Emma Stone", "Mark Ruffalo", "Willem Dafoe"], poster: "https://via.placeholder.com/300x450/1e0a2e/b04fc8?text=Poor+Things", backdrop: "https://via.placeholder.com/1400x600/120618/b04fc8?text=Poor+Things", desc: "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life.", trending: true, color: "#b04fc8" },
  { id: 4, title: "Past Lives", year: 2023, rating: 7.9, genre: ["Romance", "Drama"], runtime: "1h 46m", director: "Celine Song", cast: ["Greta Lee", "Teo Yoo", "John Magaro"], poster: "https://via.placeholder.com/300x450/0a1a2e/4a8ec8?text=Past+Lives", backdrop: "https://via.placeholder.com/1400x600/06101a/4a8ec8?text=Past+Lives", desc: "Two childhood friends from South Korea meet again over three decades and grapple with love and destiny.", trending: false, color: "#4a8ec8" },
  { id: 5, title: "The Zone of Interest", year: 2023, rating: 7.9, genre: ["Drama", "History"], runtime: "1h 45m", director: "Jonathan Glazer", cast: ["Sandra Hüller", "Christian Friedel"], poster: "https://via.placeholder.com/300x450/1a1a1a/cccccc?text=Zone+of+Interest", backdrop: "https://via.placeholder.com/1400x600/111111/cccccc?text=Zone+of+Interest", desc: "A Nazi commandant and his wife build their ideal life next to the Auschwitz concentration camp.", trending: false, color: "#aaaaaa" },
  { id: 6, title: "Killers of the Flower Moon", year: 2023, rating: 7.6, genre: ["Crime", "Drama"], runtime: "3h 26m", director: "Martin Scorsese", cast: ["Leonardo DiCaprio", "Robert De Niro", "Lily Gladstone"], poster: "https://via.placeholder.com/300x450/1a0a00/e84a00?text=Killers+Moon", backdrop: "https://via.placeholder.com/1400x600/110600/e84a00?text=Killers+Moon", desc: "Members of the Osage Nation are murdered under mysterious circumstances in the 1920s sparking a major FBI investigation.", trending: true, color: "#e84a00" },
  { id: 7, title: "Anatomy of a Fall", year: 2023, rating: 7.7, genre: ["Thriller", "Drama"], runtime: "2h 31m", director: "Justine Triet", cast: ["Sandra Hüller", "Swann Arlaud"], poster: "https://via.placeholder.com/300x450/1a1a0a/c8b84e?text=Anatomy+Fall", backdrop: "https://via.placeholder.com/1400x600/111109/c8b84e?text=Anatomy+Fall", desc: "A woman suspected of her husband's murder and the blind son who witnessed the incident must determine what truly happened.", trending: false, color: "#c8b84e" },
  { id: 8, title: "The Holdovers", year: 2023, rating: 7.8, genre: ["Comedy", "Drama"], runtime: "2h 13m", director: "Alexander Payne", cast: ["Paul Giamatti", "Da'Vine Joy Randolph"], poster: "https://via.placeholder.com/300x450/0a1a0a/4ec84e?text=The+Holdovers", backdrop: "https://via.placeholder.com/1400x600/060e06/4ec84e?text=The+Holdovers", desc: "A curmudgeonly instructor at a 1970s New England prep school is forced to remain on campus over the holidays.", trending: false, color: "#4ec84e" },
  { id: 9, title: "American Fiction", year: 2023, rating: 7.4, genre: ["Comedy", "Drama"], runtime: "1h 57m", director: "Cord Jefferson", cast: ["Jeffrey Wright", "Tracee Ellis Ross"], poster: "https://via.placeholder.com/300x450/1a0a1a/c84ea0?text=American+Fiction", backdrop: "https://via.placeholder.com/1400x600/100610/c84ea0?text=American+Fiction", desc: "A novelist frustrated with the African American experience being treated as entertainment writes a mockery of racial stereotypes.", trending: true, color: "#c84ea0" },
  { id: 10, title: "Barbie", year: 2023, rating: 6.9, genre: ["Comedy", "Fantasy"], runtime: "1h 54m", director: "Greta Gerwig", cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera"], poster: "https://via.placeholder.com/300x450/1a0a15/ff69b4?text=Barbie", backdrop: "https://via.placeholder.com/1400x600/110910/ff69b4?text=Barbie", desc: "Barbie suffers a crisis and sets out on a journey of self-discovery in the real world.", trending: true, color: "#ff69b4" },

  // Top Rated Classics
  { id: 11, title: "The Shawshank Redemption", year: 1994, rating: 9.3, genre: ["Drama"], runtime: "2h 22m", director: "Frank Darabont", cast: ["Tim Robbins", "Morgan Freeman"], poster: "https://via.placeholder.com/300x450/0f1a0f/50c850?text=Shawshank", backdrop: "https://via.placeholder.com/1400x600/090e09/50c850?text=Shawshank", desc: "Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.", trending: false, color: "#50c850" },
  { id: 12, title: "The Godfather", year: 1972, rating: 9.2, genre: ["Crime", "Drama"], runtime: "2h 55m", director: "Francis Ford Coppola", cast: ["Marlon Brando", "Al Pacino", "James Caan"], poster: "https://via.placeholder.com/300x450/1a0000/e84a00?text=Godfather", backdrop: "https://via.placeholder.com/1400x600/110000/e84a00?text=Godfather", desc: "The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.", trending: false, color: "#e84a00" },
  { id: 13, title: "Schindler's List", year: 1993, rating: 9.0, genre: ["Drama", "History"], runtime: "3h 15m", director: "Steven Spielberg", cast: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley"], poster: "https://via.placeholder.com/300x450/1a1a1a/ffffff?text=Schindler", backdrop: "https://via.placeholder.com/1400x600/111111/ffffff?text=Schindler", desc: "In German-occupied Poland during World War II, industrialist Oskar Schindler shelters Jewish refugees.", trending: false, color: "#dddddd" },
  { id: 14, title: "Pulp Fiction", year: 1994, rating: 8.9, genre: ["Crime", "Thriller"], runtime: "2h 34m", director: "Quentin Tarantino", cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"], poster: "https://via.placeholder.com/300x450/1a1500/e8c800?text=Pulp+Fiction", backdrop: "https://via.placeholder.com/1400x600/110e00/e8c800?text=Pulp+Fiction", desc: "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four tales of violence.", trending: false, color: "#e8c800" },
  { id: 15, title: "The Dark Knight", year: 2008, rating: 9.0, genre: ["Action", "Sci-Fi"], runtime: "2h 32m", director: "Christopher Nolan", cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"], poster: "https://via.placeholder.com/300x450/050511/4a8ec8?text=Dark+Knight", backdrop: "https://via.placeholder.com/1400x600/030308/4a8ec8?text=Dark+Knight", desc: "Batman faces the Joker, a criminal mastermind who plunges Gotham into anarchy and tests Batman's moral limits.", trending: false, color: "#4a8ec8" },
  { id: 16, title: "Inception", year: 2010, rating: 8.8, genre: ["Sci-Fi", "Thriller"], runtime: "2h 28m", director: "Christopher Nolan", cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"], poster: "https://via.placeholder.com/300x450/0a0a1a/5a5ac8?text=Inception", backdrop: "https://via.placeholder.com/1400x600/060610/5a5ac8?text=Inception", desc: "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.", trending: false, color: "#5a5ac8" },
  { id: 17, title: "Interstellar", year: 2014, rating: 8.7, genre: ["Sci-Fi", "Drama"], runtime: "2h 49m", director: "Christopher Nolan", cast: ["Matthew McConaughey", "Anne Hathaway"], poster: "https://via.placeholder.com/300x450/0a0f1a/87ceeb?text=Interstellar", backdrop: "https://via.placeholder.com/1400x600/060a11/87ceeb?text=Interstellar", desc: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", trending: false, color: "#87ceeb" },
  { id: 18, title: "Parasite", year: 2019, rating: 8.5, genre: ["Drama", "Thriller"], runtime: "2h 12m", director: "Bong Joon-ho", cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"], poster: "https://via.placeholder.com/300x450/1a0a00/ff8000?text=Parasite", backdrop: "https://via.placeholder.com/1400x600/110600/ff8000?text=Parasite", desc: "A poor family schemes to become employed by a wealthy family by infiltrating their household one by one.", trending: false, color: "#ff8000" },
  { id: 19, title: "Everything Everywhere All at Once", year: 2022, rating: 7.8, genre: ["Sci-Fi", "Comedy"], runtime: "2h 19m", director: "The Daniels", cast: ["Michelle Yeoh", "Ke Huy Quan", "Jamie Lee Curtis"], poster: "https://via.placeholder.com/300x450/0a1a10/3ec87a?text=EEAAO", backdrop: "https://via.placeholder.com/1400x600/060e0a/3ec87a?text=EEAAO", desc: "A middle-aged Chinese immigrant is swept up in an adventure to save the world by exploring other universes.", trending: false, color: "#3ec87a" },
  { id: 20, title: "Whiplash", year: 2014, rating: 8.5, genre: ["Drama", "Music"], runtime: "1h 47m", director: "Damien Chazelle", cast: ["Miles Teller", "J.K. Simmons"], poster: "https://via.placeholder.com/300x450/1a0000/e80000?text=Whiplash", backdrop: "https://via.placeholder.com/1400x600/110000/e80000?text=Whiplash", desc: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams and determination are put to the test.", trending: false, color: "#e80000" },

  // More recent
  { id: 21, title: "Saltburn", year: 2023, rating: 7.1, genre: ["Thriller", "Drama"], runtime: "2h 11m", director: "Emerald Fennell", cast: ["Barry Keoghan", "Jacob Elordi"], poster: "https://via.placeholder.com/300x450/1a1700/c8b800?text=Saltburn", backdrop: "https://via.placeholder.com/1400x600/111000/c8b800?text=Saltburn", desc: "A student who wins a scholarship to Oxford becomes enamored with his charming classmate and spends the summer at his family estate.", trending: true, color: "#c8b800" },
  { id: 22, title: "Priscilla", year: 2023, rating: 6.8, genre: ["Drama", "Romance"], runtime: "1h 53m", director: "Sofia Coppola", cast: ["Cailee Spaeny", "Jacob Elordi"], poster: "https://via.placeholder.com/300x450/1a0a10/d45090?text=Priscilla", backdrop: "https://via.placeholder.com/1400x600/110610/d45090?text=Priscilla", desc: "The story of Priscilla Presley's life with Elvis, from their first meeting to the early days of their marriage.", trending: false, color: "#d45090" },
  { id: 23, title: "May December", year: 2023, rating: 6.9, genre: ["Drama"], runtime: "1h 57m", director: "Todd Haynes", cast: ["Natalie Portman", "Julianne Moore", "Charles Melton"], poster: "https://via.placeholder.com/300x450/0a1a0a/5ac850?text=May+December", backdrop: "https://via.placeholder.com/1400x600/060e06/5ac850?text=May+December", desc: "An actress who is about to play a famous woman visits her subject to learn about the infamous scandal that made headlines.", trending: false, color: "#5ac850" },
  { id: 24, title: "Society of the Snow", year: 2023, rating: 7.9, genre: ["Drama", "History"], runtime: "2h 24m", director: "J.A. Bayona", cast: ["Agustín Pardella", "Matías Recalt"], poster: "https://via.placeholder.com/300x450/0a0f1a/a0b8cc?text=Society+Snow", backdrop: "https://via.placeholder.com/1400x600/06090e/a0b8cc?text=Society+Snow", desc: "A Uruguayan rugby team's plane crashes in the Andes. Trapped and desperate, survivors must make unthinkable decisions.", trending: true, color: "#a0b8cc" },
  { id: 25, title: "A Haunting in Venice", year: 2023, rating: 6.8, genre: ["Mystery", "Thriller"], runtime: "1h 43m", director: "Kenneth Branagh", cast: ["Kenneth Branagh", "Tina Fey"], poster: "https://via.placeholder.com/300x450/0a0a1a/6464c8?text=Haunting+Venice", backdrop: "https://via.placeholder.com/1400x600/06060e/6464c8?text=Haunting+Venice", desc: "In 1947 Venice, retired detective Hercule Poirot attends a seance but becomes entangled in a mysterious murder.", trending: false, color: "#6464c8" },
];

const heroMovies = MOVIES.filter(m => m.trending).slice(0, 5);
const trendingMovies = MOVIES.filter(m => m.trending);
const topRatedMovies = [...MOVIES].sort((a, b) => b.rating - a.rating).slice(0, 10);
const classicsMovies = MOVIES.filter(m => m.year < 2020).sort((a, b) => b.rating - a.rating).slice(0, 10);

const ALL_GENRES = [...new Set(MOVIES.flatMap(m => m.genre))].sort();
